repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # It's good to pin to a specific version for stability
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0 # Always pin to a specific, stable version
    hooks:
      - id: detect-secrets
        # --- IMPORTANT CORRECTION HERE ---
        # Add the 'args' to include the baseline file
        args: ['--baseline', '.secrets.baseline']
